### ISSUE TITLE
Matched search text is padded with whitespace

### ISSUE THREAD

**Issue by guitar486** [fm4d/KickassAPI#13]
On the website, matched search text is highlighted in red.  For some reason, this feature seems to return extra whitespace surrounding any matching search text within the torrent name.

Example search: 
<img width="103" alt="screen shot 2015-07-21 at 12 41 21 pm" src="https://cloud.githubusercontent.com/assets/7351161/8810773/3cde06d6-2fa6-11e5-8594-8873e14011ac.png">
How it looks on website (Even though I'm searching for a date, "20" appears elsewhere:
<img width="44" alt="screen shot 2015-07-21 at 12 41 31 pm" src="https://cloud.githubusercontent.com/assets/7351161/8810786/4ff67bfe-2fa6-11e5-8dad-3be174f77ae6.png">
How it manifests programatically:
<img width="45" alt="screen shot 2015-07-21 at 12 41 41 pm" src="https://cloud.githubusercontent.com/assets/7351161/8810802/6d7332e4-2fa6-11e5-9512-0b46e03d0c06.png">

This breaks my program when I'm searching for "720p" in a torrent name.  I'm sure I can code around this, but if it's an easy fix on the API end that would be awesome!  Love and appreciate all the work you do, thank you!

**Comment by fm4d** [comment]
Hey, thanks for support. I am currently rewriting the api so I will definitely check this issue and solve it. Not sure about release date, but probably something about 7-10 days :)

**Comment by guitar486** [comment]
Awesome! Thanks for the fast response :)
