### ISSUE TITLE
Magnet Links Changed?

### ISSUE THREAD

**Issue by srob650** [fm4d/KickassAPI#14]
It seems like kat.cr may have changed the way they list magnet links within the last couple of days, because all torrents return "magnet_link=None" all of a sudden.  Hope all is coming along well with the API overhaul and this doesn't throw a wrench in anything!  I'm hosed without the magnet links so if you need an early beta tester let me know :)

**Comment by arthurv89** [comment]
The link can no longer be found using the "a.imagnet.icon16" selector. Probably better to look for links that start with "magnet:" in the href.

**Comment by guitar486** [comment]
I could kiss you

**Comment by arthurv89** [comment]
Was actually my first piece of Python code and first Github contribution ever :)

**Comment by guitar486** [comment]
Hah awesome, congrats!  

I am a novice self-taught programmer as a hobby and I had just gotten around the issue in my program using BeautifulSoup and the fact that the magnet link would always be the first one in the torrent_link html.  Going to keep it in my program in case this ever pops up again :)

**Comment by miguelripoll** [comment]
@arthurv89 I want to kiss you too!

What you guys use this API for? I'm using it for download TV shows as you can see on my profile, I'm really curious about you.

**Comment by vinigfer** [comment]
Has this been fixed? Can you send a pull request to merge it to this project and close this issue?

**Comment by rom1504** [comment]
this has been fixed and broken again I believe ;)

**Comment by vinigfer** [comment]
Another change in KickassTorrent site? Or just a mistake in the code.

**Comment by vinigfer** [comment]
A mistake in the code. I changed it directly in my /usr/local/lib/python2.7/dist-packages/KickassAPI.py file, erased the .pyc file with the same name, and it worked!

**Comment by srob650** [comment]
FYI the owner of this repo claimed he would no longer be maintaining this project.  I have created a [Python interface to torrentz.eu](https://github.com/srob650/pytorrentz) that fills the void for me.  Feel free to contribute to it if you have improvements!

**Comment by vinigfer** [comment]
Thanks @srob650! I prefer KickassTorrent, but since torrentz.eu index several engines, I'll definitely check it out.

**Comment by srob650** [comment]
@vinigfer I had the same preference before but it turns out the API for torrentz.eu is **significantly** faster than KAT.
