### ISSUE TITLE
Requests for the rewrite :)

### ISSUE THREAD

**Issue by srob650** [fm4d/KickassAPI#18]
Just some requests from a fan of your work!  And if you have an ETA on the rewrite we would all love to hear from you (and test for you), I bet some would even donate to help speed it up :)

1. Would love to be able to get the data on how many "thumbs-up/down" and "report fake" there are.  
<img width="140" alt="screen shot 2015-09-08 at 5 44 05 pm" src="https://cloud.githubusercontent.com/assets/7351161/9750795/a27c848c-5651-11e5-90c1-58f3334d0f8c.png">
2. Would love to get access to comments to be able to regex through them for another step of scoring.
3. It seems like the verified_torrent and verified_author properties don't work currently, will they stay in the new version?

Thanks as always!

**Comment by fm4d** [comment]
Thanks for tips/requests, I was kind of busy/afk last few weeks but I believe I will dive into the rewrite soon. 
1. Thumbs up/down are just matter of parsing, but I am not even sure there are any data about 'report fake', I think it is just a way how to report torrent to administrators.
2. Yes, comments will be included.
3. Ill look into this.

**Comment by guitar486** [comment]
Thank you thank you!
