### ISSUE TITLE
Any news on the rewrite? :)

### ISSUE THREAD

**Issue by srob650** [fm4d/KickassAPI#23]
Just checking in for an update

**Comment by fm4d** [comment]
I have bad message for you, during the rewrite I found so many disgusting hacks and nonsenses in kat.cr web that without really nasty hacks it was basically impossible to implement the features that were planned - comments, detailed torrent info and others. And then I totally changed my workflow (implemented simple api in elisp) and stopped using this python api at all so this (outdated and bugged) version of this api is the final version.

**Comment by srob650** [comment]
That's ok, thanks for the update.  I actually wrote a really basic one for torrentz.eu that I'm using now :)
